# Generated by Django 4.0.3 on 2022-06-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(null=True, to='shop.category'),
        ),
    ]
