# Generated by Django 4.0.3 on 2022-06-16 04:32

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '&#9734;'), (2, '&#9734;'), (3, '&#9734;'), (4, '&#9734;'), (5, '&#9734;')], default=0, validators=[shop.models.validate_rating]),
        ),
    ]
